remote_theme: pages-themes/primer@v0.2.0
plugins:
<<<<<<< HEAD
- jekyll-remote-theme # add this line to the plugins list if you already have one
=======
- jekyll-remote-theme # add this line to the plugins list if you already have one
>>>>>>> abc1650ec1fe443193a1c39277b4c483d7f32ec1
